export const SET_LEFT_TRACKS = 'SET_LEFT_TRACKS';
export const REMOVE_LEFT_TRACK = 'REMOVE_LEFT_TRACK';

export const SET_RIGHT_TRACKS = 'SET_RIGHT_TRACKS';
export const REMOVE_RIGHT_TRACK = 'REMOVE_RIGHT_TRACK';